python -m torch.distributed.launch --nproc_per_node=4 --master_port=12233 --use_env run_train.py \
--diff_steps 500 \
--lr 1e-4 \
--learning_steps 50000 \
--save_interval 5000 \
--seed 102 \
--noise_schedule sqrt \
--hidden_dim 128 \
--bsz 1024 \
--dataset qqp \
--data_dir datasets/QQP \
--vocab bert \
--seq_len 128 \
--schedule_sampler lossaware \
--notes frozen-bert-qqp \
--use_plm_init bert 
